sonar.projectKey=freepbx-callpanel
sonar.projectName=FreePBX Calls + Contacts Panel
sonar.projectVersion=17.0.2
sonar.sources=.
sonar.sourceEncoding=UTF-8
sonar.exclusions=**/node_modules/**,**/build/**,**/screenshots/**,**/*.min.js,**/*.min.css,**/package-lock.json,specs/**,docs/**,.github/**
sonar.host.url=http://10.32.161.205:9000
